/*
UPDATE sessions                 SET log_id          = NULL;
UPDATE uploaded_file_sheets     SET result_log_id   = NULL;
--
DROP TABLE logs_events  PURGE;
DROP TABLE logs_lobs    PURGE;
DROP TABLE logs_setup   PURGE;
DROP TABLE sessions     PURGE;
DROP TABLE logs         PURGE;
*/
CREATE TABLE logs (
    log_id              INTEGER         CONSTRAINT nn_logs_log_id       NOT NULL,   -- NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL
    log_parent          INTEGER,                                                    -- DONT PUT FK ON IT TO AVOID DEADLOCKS
    --
    app_id              NUMBER(4)       CONSTRAINT nn_logs_app_id       NOT NULL,
    user_id             VARCHAR2(30)    CONSTRAINT nn_logs_user_id      NOT NULL,
    page_id             NUMBER(6)       CONSTRAINT nn_logs_page_id      NOT NULL,
    flag                CHAR(1)         CONSTRAINT nn_logs_flag         NOT NULL,
    --
    action_name         VARCHAR2(32)    CONSTRAINT nn_logs_action_name  NOT NULL,   -- 32 chars, DBMS_APPLICATION_INFO limit
    module_name         VARCHAR2(64)    CONSTRAINT nn_logs_module_name  NOT NULL,   -- 48 chars, DBMS_APPLICATION_INFO limit
    module_line         NUMBER(8)       CONSTRAINT nn_logs_module_line  NOT NULL,
    --
    arguments           VARCHAR2(1000),
    message             VARCHAR2(4000),
    --
    session_id          NUMBER,
    --
    timer               VARCHAR2(15),
    created_at          TIMESTAMP       CONSTRAINT nn_logs_created_at   NOT NULL,
    today               VARCHAR2(10)    CONSTRAINT nn_logs_today        NOT NULL,
    --
    CONSTRAINT pk_logs
        PRIMARY KEY (log_id)
    /**
    SELECT n.table_name, n.constraint_name
    FROM user_constraints n
    WHERE n.r_constraint_name = 'PK_LOGS';
    */
    --
    -- NO MORE CONSTRAINTS TO KEEP THIS AS FAST AS POSSIBLE
    --
)
/*
PARTITION BY RANGE (created_at)
INTERVAL (NUMTODSINTERVAL(1, 'DAY')) (
    PARTITION P00 VALUES LESS THAN (TIMESTAMP '2020-01-01 00:00:00')
*/
PARTITION BY LIST (today, app_id) AUTOMATIC (
    PARTITION "P_20200101_700"  VALUES (('2020-01-01', 700)) SEGMENT CREATION IMMEDIATE
);
--
COMMENT ON TABLE  logs                  IS 'Messages raised in application; daily partitions';
--
COMMENT ON COLUMN logs.log_id           IS 'Log ID generated from `LOG_ID` sequence';
COMMENT ON COLUMN logs.log_parent       IS 'Parent log record; dont use FK to avoid deadlocks';
--
COMMENT ON COLUMN logs.app_id           IS 'APEX Application ID';
COMMENT ON COLUMN logs.user_id          IS 'User ID';
COMMENT ON COLUMN logs.page_id          IS 'APEX Application PAGE ID';
COMMENT ON COLUMN logs.flag             IS 'Type of error listed in `tree` package specification; FK missing for performance reasons';
--
COMMENT ON COLUMN logs.action_name      IS 'Action name to distinguish position in module or use it as warning/error names';
COMMENT ON COLUMN logs.module_name      IS 'Module name (procedure or function name)';
COMMENT ON COLUMN logs.module_line      IS 'Line in the module';
--
COMMENT ON COLUMN logs.arguments        IS 'Arguments passed to module';
COMMENT ON COLUMN logs.message          IS 'Formatted call stack, error stack or query with DML error';
COMMENT ON COLUMN logs.session_id       IS 'Session ID (generated by APEX) from `sessions` table';
--
COMMENT ON COLUMN logs.timer            IS 'Timer for current row in seconds';
COMMENT ON COLUMN logs.created_at       IS 'Timestamp of creation';
COMMENT ON COLUMN logs.today            IS 'Date of creation';

