--DROP TABLE sessions PURGE;
CREATE TABLE sessions (
    session_id          NUMBER          NOT NULL,
    --
    user_id             VARCHAR2(30)    NOT NULL,
    app_id              NUMBER(4)       NOT NULL,       -- FK to apps
    page_id             NUMBER(6)       NOT NULL,       -- FK to app_pages
    --
    apex_items          VARCHAR2(4000),
    --
    session_db          NUMBER          NOT NULL,
    --
    created_at          TIMESTAMP       NOT NULL,
    updated_at          TIMESTAMP       NOT NULL,
    --
    CONSTRAINT pk_sessions PRIMARY KEY (session_id),
    --
    CONSTRAINT fk_sessions_users FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    --
    CONSTRAINT ch_sessions_apex_items_json CHECK (apex_items IS JSON)
);
--
CREATE INDEX fk_sessions_users ON sessions (user_id) COMPUTE STATISTICS;
--
COMMENT ON TABLE  sessions                  IS 'Sessions overview';
--
COMMENT ON COLUMN sessions.session_id       IS 'Session ID generated by APEX, used in `logs.session_id`';
COMMENT ON COLUMN sessions.user_id          IS 'User ID';
COMMENT ON COLUMN sessions.app_id           IS 'APEX application ID';
COMMENT ON COLUMN sessions.page_id          IS 'APEX page ID';
--
COMMENT ON COLUMN sessions.apex_items       IS 'APEX global items';
--
COMMENT ON COLUMN sessions.session_db       IS 'Database session ID';
--
COMMENT ON COLUMN sessions.created_at       IS 'Timestamp of creation';
COMMENT ON COLUMN sessions.updated_at       IS 'Timestamp of last update';

