--SELECT * FROM dba_tablespaces ORDER BY 1;

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
--
CREATE USER dev
    IDENTIFIED BY "D3V-super-secret-password-123"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON data;

